replicaCount: 2

image:
  repository: redis/redis-stack-server
  pullPolicy: IfNotPresent

namespace: redis
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  headless: true
  type: ClusterIP
  port: 6379

configMap:
  name: redis-stack-configuration
  mountPath: /mnt
  master:
    requirepass: 5Mm7vJI2R8
    maxMemory: 1000mb
    maxMemoryPolicy: allkeys-lru
    maxClients: 20000
    timeout: 300
    dbFileName: dump.rdb
    dir: /data
    appendOnly: "yes"
    save: ""
  replicas:
    requirepass: 5Mm7vJI2R8
    maxMemory: 1000mb
    maxMemoryPolicy: allkeys-lru
    maxClients: 20000
    timeout: 300
    dir: /data
    appendOnly: "yes"
    save: ""

# For configuration files
volumeConf:
  name: redis-claim
  request: 1Gi
  storageClassName: gp2
  mountPath: /etc

# Actual data
volumeData:
  name: redis-data
  request: 8Gi
  storageClassName: gp2
  mountPath: /var/lib/redis-stack

nodeSelector: {}

tolerations: []

affinity: {}
